dive_spot_view:
    path:     /spot/view/{id}
    defaults: { _controller: diveSpotBundle:Default:view }
    
dive_spot_add:
    path:     /spot/add
    defaults: { _controller: diveSpotBundle:Default:add }
    
dive_spot_list:
    path:     /spot/list
    defaults: { _controller: diveSpotBundle:Default:list }
