# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app_user.diver_registration_listener:
        class: AppBundle\EventListener\DiverRegistrationListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }
    app.twig.country_extension:
        class: AppBundle\Twig\CountryExtension
        tags:
            - { name: twig.extension }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
