<?php

namespace dive\LogbookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiverRepository extends EntityRepository
{
}
