<?php

namespace dive\LogbookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiveRepository extends EntityRepository
{
}
